name       : scikit-image
version    : 0.14.2
release    : 2
source     :
    - https://github.com/scikit-image/scikit-image/archive/v0.14.2.tar.gz : 469d68d1c0eeab9aa90b3d41d7dedd79233386997f190d95b110d588c3cfc89e
license    : BSD-3-Clause
component  : programming.python
summary    : Image processing in Python
description: |
    scikit-image is a collection of algorithms for image processing.
builddeps  :
    - cython
    - numpy
rundeps    :
    - matplotlib
    - networkx
    - python-pywavelets
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
