name       : scikit-image
version    : 0.19.3
release    : 9
source     :
    - https://github.com/scikit-image/scikit-image/archive/refs/tags/v0.19.3.tar.gz : 4eb877c98d1395769daef5bc2ba8a7efd3f736c87086aecb3775a9174593398b
homepage   : https://scikit-image.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Image processing in Python
description: |
    scikit-image is a collection of algorithms for image processing.
builddeps  :
    - cython
    - numpy
    - python-packaging
    - python-pythran
rundeps    :
    - networkx
    - python-imageio
    - python-pywavelets
    - python-tifffile
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
