name       : scikit-image
version    : 0.15.0
release    : 3
source     :
    - https://github.com/scikit-image/scikit-image/archive/v0.15.0.tar.gz : 312dc7c49e3abdb90a42967fcf6129f0c9a45bd65f74b0cd3591390929b31a70
license    : BSD-3-Clause
component  : programming.python
summary    : Image processing in Python
description: |
    scikit-image is a collection of algorithms for image processing.
builddeps  :
    - cython
    - numpy
rundeps    :
    - matplotlib
    - networkx
    - python-imageio
    - python-pywavelets
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
